[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
{n=G.UIT.O, config={object = DynaText({string = {' '..localize('ph_mr_bones')..' '}, colours = {G.C.FILTER}, shadow = true, pop_in = 0, scale = 0.5*scale, silent = true})}}
'''
position = "at"
match_indent = true
payload = '''
{n=G.UIT.O, config={object = DynaText({string = {' '..(config.saved_message or 'Saved!')..' '}, colours = {G.C.FILTER}, shadow = true, pop_in = 0, scale = 0.5*scale, silent = true})}}
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "saved = true,"
position = "after"
match_indent = true
payload = '''
saved_message = localize('ph_mr_bones'),
'''
