[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5"
position = "at"
match_indent = true
payload = "pseudorandom('lucky_mult') < G.GAME.probabilities.normal/self.ability.mult_odds"

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "pseudorandom('lucky_money') < G.GAME.probabilities.normal/15"
position = "at"
match_indent = true
payload = "pseudorandom('lucky_money') < G.GAME.probabilities.normal/self.ability.p_dollars_odds"
