[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = (function() check_for_unlock{type = 'upgrade_hand', hand = hand, level = G.GAME.hands[hand].level} return true end)
}))
'''
position = "after"
match_indent = true
payload = '''
for _,J in ipairs(G.jokers.cards) do
    J:calculate_joker({level_up_hand = hand, level_up_amount = amount})
end
-- print('Observatory is working.')
'''