[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if card and card.playing_card then SMODS.drawn_cards[#SMODS.drawn_cards+1] = card end"
position = "after"
match_indent = true
payload = '''
SMODS.calculate_context({card_drawn = card, facing_blind = G.GAME.facing_blind})
'''
